# Generated by Django 3.1.3 on 2021-06-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxymodel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blogapp.post',),
        ),
    ]
